os:
- linux
- osx
language: node_js
node_js:
- node
cache:
  yarn: true
sudo: false
matrix:
  fast_finish: true
script: yarn test
after_success:
- yarn global add codeclimate-test-reporter
- codeclimate-test-reporter < test/coverage/lcov.info
addons:
  code_climate:
    repo_token: d4e9d96b88184c8841c0f11761fe17e51e4f2ee53e07b5204f7049a7f286bd61
notifications:
  email: false
